# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_ver_detalles_libro.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 40, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 80, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.entrada_titulo_libro = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_titulo_libro.setEnabled(False)
        self.entrada_titulo_libro.setGeometry(QtCore.QRect(350, 90, 113, 21))
        self.entrada_titulo_libro.setObjectName("entrada_titulo_libro")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.entrada_paginas_libro = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_paginas_libro.setEnabled(False)
        self.entrada_paginas_libro.setGeometry(QtCore.QRect(350, 120, 113, 21))
        self.entrada_paginas_libro.setObjectName("entrada_paginas_libro")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(260, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entrada_precio_libro = QtWidgets.QLineEdit(self.centralwidget)
        self.entrada_precio_libro.setEnabled(False)
        self.entrada_precio_libro.setGeometry(QtCore.QRect(350, 150, 113, 21))
        self.entrada_precio_libro.setObjectName("entrada_precio_libro")
        self.checkbox_digital = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_digital.setEnabled(False)
        self.checkbox_digital.setGeometry(QtCore.QRect(350, 180, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkbox_digital.setFont(font)
        self.checkbox_digital.setObjectName("checkbox_digital")
        self.combo_tapa = QtWidgets.QComboBox(self.centralwidget)
        self.combo_tapa.setEnabled(False)
        self.combo_tapa.setGeometry(QtCore.QRect(350, 220, 121, 22))
        self.combo_tapa.setObjectName("combo_tapa")
        self.combo_tapa.addItem("")
        self.combo_tapa.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 210, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 250, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.radio_standar = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_standar.setEnabled(False)
        self.radio_standar.setGeometry(QtCore.QRect(350, 260, 201, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radio_standar.setFont(font)
        self.radio_standar.setChecked(True)
        self.radio_standar.setObjectName("radio_standar")
        self.radio_urgente = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_urgente.setEnabled(False)
        self.radio_urgente.setGeometry(QtCore.QRect(350, 290, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radio_urgente.setFont(font)
        self.radio_urgente.setObjectName("radio_urgente")
        self.radio_prioritario = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_prioritario.setEnabled(False)
        self.radio_prioritario.setGeometry(QtCore.QRect(350, 330, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radio_prioritario.setFont(font)
        self.radio_prioritario.setObjectName("radio_prioritario")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 360, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_imagen = QtWidgets.QLabel(self.centralwidget)
        self.label_imagen.setGeometry(QtCore.QRect(360, 390, 201, 111))
        self.label_imagen.setText("")
        self.label_imagen.setObjectName("label_imagen")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DETALLES DEL LIBRO:"))
        self.label_2.setText(_translate("MainWindow", "titulo:"))
        self.label_3.setText(_translate("MainWindow", "paginas:"))
        self.label_4.setText(_translate("MainWindow", "precio:"))
        self.checkbox_digital.setText(_translate("MainWindow", " version digital disponible"))
        self.combo_tapa.setItemText(0, _translate("MainWindow", "tapa blanda"))
        self.combo_tapa.setItemText(1, _translate("MainWindow", "tapa dura"))
        self.label_5.setText(_translate("MainWindow", "tapa:"))
        self.label_6.setText(_translate("MainWindow", "opcion de envio:"))
        self.radio_standar.setText(_translate("MainWindow", "Envio Standar"))
        self.radio_urgente.setText(_translate("MainWindow", "Envio Urgente"))
        self.radio_prioritario.setText(_translate("MainWindow", "Envio Prioritario"))
        self.label_7.setText(_translate("MainWindow", "Portada:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

